### ISSUE TITLE
No way back from solar system view to galaxy view

### ISSUE THREAD

**Issue by SorraTheOrc** [yolanother/OpenPath#10]
When the player moves into a solar system there is no way to get out again.

**Comment by SorraTheOrc** [comment]
Closed the wrong one

**Comment by yolanother** [comment]
Done

**Comment by SorraTheOrc** [comment]
This isn't done. Repro:

1. Go to a solar system
2. Attempt to return to the galaxy view so you can visit a different solar system

**Comment by SorraTheOrc** [comment]
It's there but a little hidden. Hamburger Menu, top right then "Star Map"
